packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@tailwindcss/postcss': ^4.1.16
  '@types/node': ^22.18.12
  dotenv-cli: ^10.0.0
  eslint: ^9.38.0
  prettier: ^3.6.2
  tailwindcss: ^4.1.16
  tsup: ^8.0.0
  tsx: ^4.20.6
  typescript: 5.9.2
  zod: 4.1.12

catalogs:
  react19:
    '@types/react': ^19.1.12
    '@types/react-dom': ^19.1.9
    next: ^16.0.0
    react: 19.1.1
    react-dom: 19.1.1

linkWorkspacePackages: true
